### ISSUE TITLE
Trouble with SSO Snowflake Authorization

### ISSUE THREAD

**Issue by knodl** [TylerHillery/harlequin-adbc#6]
Hey! Thanks for the awesome adapter. I almost managed to make it work for my case, but encountered the following error while authorizing using SSO:

I run:
```
harlequin -a adbc "somename.snowflakecomputing.com:443/mydatabase/myschema?account=myemail&authenticator=externalbrowser" --driver-type snowflake
```

And get:
```
Harlequin could not connect to your database.
IO: 390201 (08004): The requested database does not exist or not authorized.
```

Environment:
```
harlequin, version 1.21.0

Installed Adapters:
  - duckdb, version 1.21.0
  - sqlite, version 1.21.0
  - adbc, version 0.1.1
  ```
  
  Maybe I am missing something here, could you take a look please?

**Comment by TylerHillery** [comment]
Thanks for the detailed issue and bringing this to my attention. I will try to reproduce on my end and see if I can figure out a fix!

**Comment by knodl** [comment]
@binste it looks like I have access, when I run the cli command the following happens:
- I am redirected to the sso browser page
- I select the auth option
- I am redirected to the page with the message ` Your identity was confirmed and propagated to Snowflake [ADBC][Python-1.0.0]. You can close this window now and go back where you started from. ` 

The same happens when I use dbeaber, for example, but in the terminal I get `IO: 390201 (08004): The requested database does not exist or not authorized.` message

**Comment by knodl** [comment]
I figured out what was wrong in this command:
```
harlequin -a adbc "somename.snowflakecomputing.com:443/mydatabase/myschema?account=myemail&authenticator=externalbrowser" --driver-type snowflake
```

In my case it shouldn't have included `myschema`:
```
harlequin -a adbc "somename.snowflakecomputing.com:443/mydatabase?account=myemail&authenticator=externalbrowser" --driver-type snowflake
```

it works fine like this. 

So I guess, this is not a bug :) Thanks everyone who looked into this.

**Comment by TylerHillery** [comment]
@knodl Thanks for following up! Apologies for not being able to look further into myself but glad it worked out!
